// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tTrackerWeb.Database;

#nullable disable

namespace tTrackerWeb.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20231022183835_FIRST")]
    partial class FIRST
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("tTrackerWeb.Model.TimeSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimeSegments");
                });

            modelBuilder.Entity("tTrackerWeb.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AfternoonEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AfternoonStartTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("BreakDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MaxEntryTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("MaxWorkHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MorningEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MorningStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
